SELECT * FROM EMPLEADOS;

SELECT * FROM DEPARTAMENTOS;

SELECT NOMBRE_DEPTO FROM DEPARTAMENTOS;

SELECT NOMBRE,SAL_EMP FROM EMPLEADOS;

SELECT COMISION_EMP FROM EMPLEADOS;

SELECT * FROM EMPLEADOS WHERE CARGO_EMP='SECRETARIA';

SELECT * FROM EMPLEADOS WHERE CARGO_EMP='VENDEDOR' ORDER BY NOMBRE ASC;

SELECT NOMBRE,CARGO_EMP FROM EMPLEADOS ORDER BY SAL_EMP ASC;

SELECT NOMBRE_JEFE_DEPTO FROM DEPARTAMENTOS WHERE CIUDAD='CIUDAD REAL';

SELECT NOMBRE AS 'NOMBRE',CARGO_EMP AS 'CARGO' FROM EMPLEADOS;

SELECT SAL_EMP,COMISION_EMP FROM EMPLEADOS WHERE ID_DEPTO=2000 ORDER BY COMISION_EMP ASC;

SELECT NOMBRE,(SAL_EMP + COMISION_EMP + 500) AS TOTAL_A_PAGAR FROM EMPLEADOS WHERE ID_DEPTO=3000 ORDER BY NOMBRE ASC;

SELECT * FROM EMPLEADOS WHERE NOMBRE LIKE 'J%';

SELECT NOMBRE,SAL_EMP, COMISION_EMP,(SAL_EMP + COMISION_EMP) AS SALARIO_TOTAL 
FROM EMPLEADOS
WHERE COMISION_EMP > 1000;

SELECT nombre, sal_emp, comision_emp, (sal_emp + IFNULL(comision_emp, 0)) AS salario_total
FROM empleados
WHERE comision_emp IS NULL OR COMISION_EMP=0;

SELECT NOMBRE AS 'NOMBRE' FROM EMPLEADOS WHERE COMISION_EMP > SAL_EMP;

SELECT * FROM EMPLEADOS WHERE COMISION_EMP <= (SAL_EMP * 0.3);

SELECT * FROM EMPLEADOS E WHERE NOT exists(SELECT E.NOMBRE FROM EMPLEADOS WHERE E.NOMBRE LIKE '%MA%' );

SELECT * FROM DEPARTAMENTOS WHERE NOMBRE_DEPTO='VENTAS'OR NOMBRE_DEPTO='INVESTIGACION' OR NOMBRE_DEPTO='MANTENIMIENTO';

SELECT * FROM DEPARTAMENTOS D WHERE NOT EXISTS (SELECT D.NOMBRE_DEPTO FROM DEPARTAMENTOS WHERE D.NOMBRE_DEPTO='VENTAS'OR D.NOMBRE_DEPTO='INVESTIGACION' OR D.NOMBRE_DEPTO='MANTENIMIENTO');

SELECT MAX(SAL_EMP) FROM EMPLEADOS;

SELECT NOMBRE FROM EMPLEADOS ORDER BY NOMBRE DESC LIMIT 1;

SELECT (MAX(SAL_EMP) - MIN(SAL_EMP))AS DIFERENCIA FROM EMPLEADOS;

SELECT ID_DEPTO, AVG(SAL_EMP) AS 'SALARIO PROMEDIO' FROM EMPLEADOS group by ID_DEPTO;

SELECT ID_DEPTO,count(*) AS 'NUMERO DE EMPLEADOS' FROM EMPLEADOS GROUP BY ID_DEPTO HAVING COUNT(*) >3;

SELECT D.NOMBRE_DEPTO FROM DEPARTAMENTOS D LEFT JOIN EMPLEADOS E ON D.ID_DEPTO=E.ID_DEPTO WHERE E.ID_EMP IS NULL;

SELECT NOMBRE AS 'NOMBRE EMPLEADOS',ID_DEPTO AS 'DEPARTAMENTO' FROM EMPLEADOS WHERE SAL_EMP >=(SELECT AVG(SAL_EMP) FROM EMPLEADOS) ORDER BY ID_DEPTO;